#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jun 17, 2019 05:30:32 AM +03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support
import plate_detection_video
import plate_detection_single_image as imageP
from PIL import Image, ImageTk 
from tkinter import filedialog

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:


    def videoProc(self):
        path= filedialog.askopenfilename()
        plate_detection_video.prcvideo(path)

    def imageProc(self):
        path= filedialog.askopenfilename()

        self.sonuc.delete(0, self.len)

        img = Image.open(path)
        size = 450,600
        img.thumbnail(size, Image.ANTIALIAS)
        img = ImageTk.PhotoImage(img)

        self.resim1.image = img
        self.resim1.create_image(0,0, image = img, anchor = tk.NW)

        platetxt = imageP.proc_img(path)
        img2 = Image.open("dtcimg.png")
        
        img2.thumbnail(size, Image.ANTIALIAS)
        img2 = ImageTk.PhotoImage(img2)

        self.resim2.image = img2
        self.resim2.create_image(0,0, image = img2, anchor = tk.NW)

        self.len = len(platetxt)
        self.sonuc.insert(0, platetxt)

        






    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 

        top.geometry("1167x677+380+163")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.len = 0

        self.resim1 = tk.Canvas(top)
        self.resim1.place(relx=0.069, rely=0.059, relheight=0.492
                , relwidth=0.388)
        self.resim1.configure(background="#d9d9d9")
        self.resim1.configure(borderwidth="2")
        self.resim1.configure(highlightbackground="#d9d9d9")
        self.resim1.configure(highlightcolor="black")
        self.resim1.configure(insertbackground="black")
        self.resim1.configure(relief='ridge')
        self.resim1.configure(selectbackground="#c4c4c4")
        self.resim1.configure(selectforeground="black")
        self.resim1.configure(width=453)

        self.resim2 = tk.Canvas(top)
        self.resim2.place(relx=0.514, rely=0.044, relheight=0.492
                , relwidth=0.388)
        self.resim2.configure(background="#d9d9d9")
        self.resim2.configure(borderwidth="2")
        self.resim2.configure(highlightbackground="#d9d9d9")
        self.resim2.configure(highlightcolor="black")
        self.resim2.configure(insertbackground="black")
        self.resim2.configure(relief='ridge')
        self.resim2.configure(selectbackground="#c4c4c4")
        self.resim2.configure(selectforeground="black")
        self.resim2.configure(width=453)

        self.sonuc = tk.Entry(top)
        self.sonuc.place(relx=0.077, rely=0.739,height=44, relwidth=0.209)
        self.sonuc.configure(background="white")
        self.sonuc.configure(disabledforeground="#a3a3a3")
        self.sonuc.configure(font="TkFixedFont")
        self.sonuc.configure(foreground="#000000")
        self.sonuc.configure(highlightbackground="#d9d9d9")
        self.sonuc.configure(highlightcolor="black")
        self.sonuc.configure(insertbackground="black")
        self.sonuc.configure(selectbackground="#c4c4c4")
        self.sonuc.configure(selectforeground="black")

        self.plaka_lbl = tk.Label(top)
        self.plaka_lbl.place(relx=0.077, rely=0.679, height=26, width=92)
        self.plaka_lbl.configure(activebackground="#f9f9f9")
        self.plaka_lbl.configure(activeforeground="black")
        self.plaka_lbl.configure(background="#d9d9d9")
        self.plaka_lbl.configure(disabledforeground="#a3a3a3")
        self.plaka_lbl.configure(foreground="#000000")
        self.plaka_lbl.configure(highlightbackground="#d9d9d9")
        self.plaka_lbl.configure(highlightcolor="black")
        self.plaka_lbl.configure(text='''Okunan Plaka''')

        self.resim_btn = tk.Button(top)
        self.resim_btn.place(relx=0.617, rely=0.768, height=33, width=136)
        self.resim_btn.configure(activebackground="#13c1ed")
        self.resim_btn.configure(activeforeground="#000000")
        self.resim_btn.configure(background="#13c1ed")
        self.resim_btn.configure(disabledforeground="#a3a3a3")
        self.resim_btn.configure(foreground="#000000")
        self.resim_btn.configure(highlightbackground="#d9d9d9")
        self.resim_btn.configure(highlightcolor="black")
        self.resim_btn.configure(pady="0")
        self.resim_btn.configure(text='''Resim Sec''')
        self.resim_btn.configure( command = self.imageProc)

        self.video_btn = tk.Button(top)
        self.video_btn.place(relx=0.797, rely=0.768, height=33, width=126)
        self.video_btn.configure(activebackground="#ececec")
        self.video_btn.configure(activeforeground="#000000")
        self.video_btn.configure(background="#13c1ed")
        self.video_btn.configure(disabledforeground="#a3a3a3")
        self.video_btn.configure(foreground="#000000")
        self.video_btn.configure(highlightbackground="#d9d9d9")
        self.video_btn.configure(highlightcolor="black")
        self.video_btn.configure(pady="0")
        self.video_btn.configure(text='''Video Sec''')
        self.video_btn.configure( command = self.videoProc)

if __name__ == '__main__':
    vp_start_gui()





